spec:
  template:
    spec:
      containers:
      - name: external-dns
        args:
        - --log-level=info
        - --log-format=text
        - --interval=1m
        - --source=service
        - --source=ingress
        - --policy=upsert-only
        - --registry=txt
        - --provider=aws
        - --namespace=