apiVersion: v1
kind: Secret
metadata:
  name: neuro-san-secrets
  namespace: argocd
type: Opaque
data:
  # Base64 encoded OpenAI API key - replace with your actual key
  # To encode: echo -n "your-openai-api-key" | base64
  openai-api-key: "REPLACE_WITH_BASE64_ENCODED_OPENAI_KEY"
  access_key_id: "QUtJQTRYNlpQWjNRR1pLR0lBNUI="
  secret_access_key: "QlRXaWwrZGpsVkdnNXNhQnFjNzdWYUdnR0tFdEtlVUZvSENDejJKRQ=="
  region: "dXMtd2VzdC0y"
 