name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main
      - DSG-actions
      - blah-bla
  release:
    types: [published]  # Triggers when a GitHub Release is published
  workflow_dispatch:  # Allow manual runs if needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      #id-token: write  # (needed for OIDC auth)

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up variables
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "IMAGE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
            echo "IMAGE_TAG=${SHORT_SHA}" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deploy/Dockerfile
          push: true
          tags: ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

